spring:
  application:
    name: telephone-number-inventory
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/number_inventory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
    show-sql: false
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # Elasticsearch Configuration
  elasticsearch:
    rest:
      uris: http://localhost:9200
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: number-inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    root: INFO
    com.telecom.inventory: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# Application Specific Configuration
app:
  file-processing:
    chunk-size: 1000
    max-threads: 4
    temp-directory: ${java.io.tmpdir}/number-inventory
  
  elasticsearch:
    index-name: telephone_numbers
    shards: 3
    replicas: 1
  
  kafka:
    topics:
      file-processing: number-inventory-file-processing
      number-allocation: number-inventory-allocation
      status-change: number-inventory-status-change

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
